### ISSUE TITLE
$ mrhyde new starter (not work)

### ISSUE THREAD

**Issue by StartZeroGnu** [mrhydescripts/mrhyde#1]
```
$ mrhyde new starter

mrhyde/0.1.1 on Ruby 2.3.1 (2016-04-26) [i686-linux]
mrhyde/0.1.1 on Ruby 2.3.1 (2016-04-26) [i686-linux]
GET https://github.com/mrhydescripts/scripts/raw/master/starter.rb
starting new MrHyde script (sitefile) {}; lets go
Welcome, before setting up your site Mr. Hyde will ask you some questions.
Q: What's your site's title? [Your Site Title]: TestTitle
Q: What's your name? [Henry Jekyll]: TestName
Thanks! Ready-to-go. Stand back.
  handle install_theme Starter, {}
GET https://github.com/drjekyllthemes/themes/raw/master/themes.yml

*** error: *** theme 'starter' not found; sorry
```

![01](https://cloud.githubusercontent.com/assets/22280286/19981234/64d4e4ec-a201-11e6-815f-0029f364b100.png)

**Comment by geraldb** [comment]
@StartZeroGnu  Again thanks for trying and reporting. The missing starter shortcut key is now working (again). Fixed in the drjekyll gem (dependency) e.g. update drjekyll to retry. Note: I've also fixed the key for your SZ Flex (Blog) theme in scripts/sz-flex.rb. Thanks for trying. It's now working too. Try:

```
$ mrhyde new sz-flex
```

Cheers.

**Comment by StartZeroGnu** [comment]
@geraldb  Why `install_theme: szflexblog` (https://github.com/mrhydescripts/scripts/blob/master/sz-flex.rb#L15) and not `install_theme: SZ-Flex` (https://github.com/StartZeroGnu/scripts/blob/new-script/sz-flex.rb#L15)

Please read this https://github.com/StartZeroGnu/jekyll-szflex-theme/issues/1#issuecomment-260298326

**Comment by geraldb** [comment]
@StartZeroGnu  Thanks for trying.  mrhyde is still using the drjekyll themes.yml datafile and the key is the title (but slugified/urlified/downcased), thus, "SZ Flex (Blog)" becomes "szflexblog". Will add "proper" title support e.g."SZ Flex (Blog)" in the next update (to avoid confusion). Cheers.

**Comment by StartZeroGnu** [comment]
then, why you use "Starter" in the example (https://github.com/mrhydescripts/scripts/blob/master/starter.rb#L14) and do not use, "henrysstarterminimal" ???

**Comment by geraldb** [comment]
@StartZeroGnu  Sorry that's a special case (that is, it's hard-coded) see https://github.com/drjekyllthemes/drjekyll/blob/master/lib/drjekyll/catalog.rb#L42. Cheers. PS: I added a (custom) shortcut for your theme (see themes.yml) e.g.  

```
 keys: [szflex]
```

Now you should also be able to use szflex (or SZFlex etc.) if you prefer.

**Comment by StartZeroGnu** [comment]
That was my confusion... so I used `install_theme: SZ-Flex` and made him the title "SZ-Flex (Blog)" thinking that by finding "SZ-Flex" in the title install the theme.

then now with "key" I can customize the name, to use "SZ-Flex" e.g.

```
in sz-flex.rb

install_theme: "SZ-Flex"
```

and

```
in themes.yml

keys: [SZ-Flex]
```

or I can't use "-" ?  It must be SZFlex?

**Thanks for your time, and thank you so much for your patience with me, I am aware that I can be a bit heavy (sorry)**

**Comment by geraldb** [comment]
@StartZeroGnu  No worries. Thank you for your patience and trying it out and thinking it all through. The idea of the key / keys for now is to use only a-z (letters, all downcased) and 0-9 (numbers), thus, szflex. Adding a dash (-) might be an option for the future (needs an update). Cheers.
